---

- name: Install packages required by the Django app inside virtualenv
  pip: executable=pip3 virtualenv={{ virtualenv_path }} requirements={{ item }}
  with_items: requirements_files

- name: Create the Gunicorn script file
  template: src=settings.py.j2
            dest={{ django_settings_file }}
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_module }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Load Django fixtures
  django_manage:
    command: loaddata
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_module }}"
    fixtures: "fixtures.json"
  environment: django_environment
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_module }}"
  environment: django_environment
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic
