---
- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  register: sigma_front_dependencies_installed
  with_items: [ 'git' , 'npm' , 'nodejs']

- name: Setup git repository
  git: repo="{{ sigma_front_git }}" dest="{{ sigma_front_dir }}" update=yes track_submodules=yes
  when: sigma_front_dependencies_installed